### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by Korijn** [conda-forge/tectonic-feedstock#5]
Any reason there is no Windows support?

**Comment by pkgw** [comment]
The upstream package doesn't yet support Windows — cf tectonic-typesetting/tectonic#32. It could and should do so, but there's just a lack of person-power to do it.

Once Tectonic does support Windows, this package will definitely be updated to add it as a supported platform. Although [the rust feedstock](https://github.com/conda-forge/rust-feedstock) will need to gain Windows support first.
